### ISSUE TITLE
Wrong Cache Path For Gitlab CI

### ISSUE THREAD

**Issue by christophfroehlichh** [platformio/platformio-docs#377]
The current documentation at [link](https://docs.platformio.org/en/latest/integration/ci/gitlab.html) provides a cache path that does not work in GitLab, preventing us from using caching.

```
image: python:3.11

cache:
  paths:
    - ~/.cache/pip
    - ~/.platformio/.cache

stages:
  - build

before_script:
  - "pip install -U platformio==6.1.16"

job:
  stage: build
  script:
    - "pio run -d examples/hello-world -e rpipico2"
```

![Image](https://github.com/user-attachments/assets/4259bf7b-69b5-4a03-998a-1739cb6d771b)

![Image](https://github.com/user-attachments/assets/d8941799-5074-46f1-a725-986e376e84bc)

A working path would be awesome! :)

**Comment by valeros** [comment]
Hi @christophfroehlichh, thanks for pointing it out. It seems that GitLabs have a restriction on cache locations, so that the cache should be local now to the project root. Updated docs with fixed configurations is coming soon, in the meantime, you can use the following example:
```yml
image: python:3.11

cache:
  paths:
    - .cache/pip
    - .cache/platformio

stages:
  - test

before_script:
  - "pip install -U platformio"

job:
  stage: test
  script: "pio run -d arduino-blink"

# Change cache directories to be inside the project directory since GitLab can only cache local items.
variables:  
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PLATFORMIO_CACHE_DIR: "$CI_PROJECT_DIR/.cache/platformio"

```
